Closes #79:
Alignak-monitoring-contrib/alignak-module-ws pull request #83
Opened 2017-10-27 16:08 UTC by mohierf

- check that the backend is used with the WS client credentials
- set test user as non admin with correct CRUD

2017-11-09 21:22 UTC, ddurieux requested changes

2017-11-09 21:22 UTC, ddurieux commented on alignak_module_ws/ws.py
> +            # self.backend_available = False
Remove instead comment ;)

2017-11-09 21:22 UTC, ddurieux commented on alignak_module_ws/ws.py
> +            # if not self.backend_available:
Same here, delete instead comment

2017-11-10 04:49 UTC, mohierf commented on alignak_module_ws/ws.py
> +            # self.backend_available = False
Ok

2017-11-10 04:51 UTC, mohierf commented
I made the required modifications and I will merge this PR

2017-11-10 05:24 UTC, merged

2017-11-10 05:53 UTC, ddurieux commented
It will be better to squash before merge, but it's too late :(

2017-11-10 06:42 UTC, mohierf commented
Too late :( This is because this branch was rebased on develop ... quite strange indeed!